# Generated by Django 5.2.5 on 2025-08-07 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HopeStory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("depression", "Depression Recovery"),
                            ("anxiety", "Anxiety Management"),
                            ("grief", "Grief and Loss"),
                            ("trauma", "Trauma Recovery"),
                            ("addiction", "Addiction Recovery"),
                        ],
                        max_length=20,
                    ),
                ),
                ("preview", models.TextField(max_length=500)),
                ("full_story", models.TextField()),
                ("author_pseudonym", models.CharField(max_length=100)),
                ("is_published", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Hope Stories",
                "ordering": ["-created_at"],
            },
        ),
    ]
