# Generated by Django 5.2.5 on 2025-08-07 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BreathingExercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("instructions", models.TextField()),
                ("duration_minutes", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="CopingStrategy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("anxiety", "Anxiety"),
                            ("depression", "Depression"),
                            ("grief", "Grief"),
                            ("stress", "Stress"),
                            ("general", "General"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("steps", models.TextField()),
                (
                    "difficulty_level",
                    models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)]),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
